### ISSUE TITLE
React DOM Exception in [bal-radio-group]

### ISSUE THREAD

**Issue by chester23491** [baloise-incubator/design-system#1090]
Since the `checked` property was removed, we need to use the [bal-radio-group] (https://github.com/baloise-incubator/design-system/issues/1089). 

Unfortunately we are getting a React DOM Exception, when we try to remove a [bal-radio] inside the [bal-radio-group] component:

```bash
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (http://localhost:3000/static/js/bundle.js:24868:22)
    at commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37585:19)
    at recursivelyTraverseDeletionEffects (http://localhost:3000/static/js/bundle.js:37546:9)
    at commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37685:13)
    at recursivelyTraverseDeletionEffects (http://localhost:3000/static/js/bundle.js:37546:9)
    at commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37670:13)
    at commitDeletionEffects (http://localhost:3000/static/js/bundle.js:37534:9)
    at recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:37809:13)
    at commitMutationEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37896:13)
    at recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:37823:11)
(anonymous) @ react-dom.development.js:22839
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
reportUncaughtErrorInDEV @ react-dom.development.js:22838
captureCommitPhaseError @ react-dom.development.js:27126
recursivelyTraverseMutationEffects @ react-dom.development.js:24261
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24432
commitMutationEffects @ react-dom.development.js:24243
commitRootImpl @ react-dom.development.js:26810
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:12021
batchedUpdates$1 @ react-dom.development.js:26148
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
react-dom.development.js:18687 The above error occurred in the <ForwardRef(BalRadio)> component:

    at BalRadio
    at bal-radio-group
    at d (http://localhost:3000/static/js/bundle.js:1792:7)
    at BalRadioGroup
    at bal-card
    at d (http://localhost:3000/static/js/bundle.js:1792:7)
    at BalCard
    at main
    at bal-app
    at d (http://localhost:3000/static/js/bundle.js:1792:7)
    at BalApp
    at App (http://localhost:3000/static/js/bundle.js:873:76)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundarie
```

# Example:

```ts
  const [radioList, setRadioList] = React.useState<Array<string> | undefined>([
    "Apple",
    "Orange",
    "Banana",
  ]);

return(
        <BalCard class="mt-6">
          <BalRadioGroup>
            {radioList?.map((radio) => (
              <BalRadio key={radio} value={radio}>
                {radio}
              </BalRadio>
            ))}
          </BalRadioGroup>
          <BalButton
          onClick={() => setRadioList(["Apple", "Orange", "Banana", "Cherry"])}
        >
          add cherry
        </BalButton>
        <BalButton onClick={() => setRadioList(["Apple", "Orange", "Banana"])}>
          remove cherry
        </BalButton>
        </BalCard>
);

```

**Comment by chester23491** [comment]
The ionic framework is capable to manage this operations:

```ts
const Main: React.FC<MainProps> = () => {
  const [radioList, setRadioList] = React.useState<Array<string> | undefined>([
    'Apple',
    'Orange',
    'Banana',
  ]);

  return (
    <IonPage>
      <IonRadioGroup>
        {radioList?.map((radio) => (
          <IonRadio key={radio} value={radio}>
            {radio}
          </IonRadio>
        ))}
      </IonRadioGroup>
      <IonButton onClick={() => setRadioList(['Apple', 'Orange', 'Banana', 'Cherry'])}>
        add cherry
      </IonButton>
      <IonButton onClick={() => setRadioList(['Apple', 'Orange', 'Banana'])}>
        remove cherry
      </IonButton>
    </IonPage>
  );
};
```

**Comment by hirsch88** [comment]
Hi @chester23491 

To improve that we need to enable Shadow DOM, but we are not there yet. So as a workaround wrap it with a DIV.

```jsx
const [radioList, setRadioList] = React.useState<Array<string> | undefined>([
    "Apple",
    "Orange",
    "Banana",
]);

return(
        <BalCard class="mt-6">
          <BalRadioGroup>
            <div class="bal-radio-checkbox-group__inner">
              {radioList?.map((radio) => (
                <BalRadio key={radio} value={radio}>
                  {radio}
                </BalRadio>
              ))}
            </div>
          </BalRadioGroup>
          <BalButton
          onClick={() => setRadioList(["Apple", "Orange", "Banana", "Cherry"])}
        >
          add cherry
        </BalButton>
        <BalButton onClick={() => setRadioList(["Apple", "Orange", "Banana"])}>
          remove cherry
        </BalButton>
        </BalCard>
);
```

**Comment by chester23491** [comment]
Hi @hirsch88 
Thank you for the workaround. The div is working in this case. 

I did some tests with this workaround in mind:

## [bal-select] with [bal-select-option]

I fund the same DOM exception in the [bal-select-option]. So the workaround should be here `<div className="bal-select__inner">`?

## [bal-tabs] with [bal-tab-item]

However the workaround is not working here with [bal-tabs] and [bal-tab-item]. Here even the `add cherry` is not working:
```
const [radioList, setRadioList] = React.useState<Array<string> | undefined>([
  "Apple",
  "Orange",
  "Banana",
]);
return(
<BalCard class="mt-6">
  <BalTabs>
    {radioList?.map((radio) => (
      <BalTabItem value={radio} label={radio}>
        {radio}
      </BalTabItem>
    ))}
  </BalTabs>
</BalCard>
<BalCard class="mt-6">
  <BalButton
    onClick={() =>
      setRadioList(["Apple", "Orange", "Banana", "Cherry"])
    }
  >
    add cherry
  </BalButton>
  <BalButton
    onClick={() => setRadioList(["Apple", "Orange", "Banana"])}
  >
    remove cherry
  </BalButton>
</BalCard>
);
```

## [bal-carousel] with [bal-carousel-item]

Workaround with the div is breaking the carousel - DOM exception is thrown:

```bash
react-dom.development.js:22839 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (http://localhost:3000/static/js/bundle.js:24892:22)
    at commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37609:19)
    at recursivelyTraverseDeletionEffects (http://localhost:3000/static/js/bundle.js:37570:9)
    at commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37709:13)
    at recursivelyTraverseDeletionEffects (http://localhost:3000/static/js/bundle.js:37570:9)
    at commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:37694:13)
    at commitDeletionEffects (http://localhost:3000/static/js/bundle.js:37558:9)
    at recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:37833:13)
    at commitMutationEffectsOnFiber (http://localhost:3000/static/js/bundle.js:38145:13)
    at recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:37847:11)
(anonymous) @ react-dom.development.js:22839
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
reportUncaughtErrorInDEV @ react-dom.development.js:22838
captureCommitPhaseError @ react-dom.development.js:27126
recursivelyTraverseMutationEffects @ react-dom.development.js:24261
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24432
commitMutationEffects @ react-dom.development.js:24243
commitRootImpl @ react-dom.development.js:26810
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:12021
batchedUpdates$1 @ react-dom.development.js:26148
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
react-dom.development.js:18687 The above error occurred in the <ForwardRef(BalCarouselItem)> component:

    at BalCarouselItem
    at bal-carousel
    at d (http://localhost:3000/static/js/bundle.js:1816:7)
    at BalCarousel
    at bal-card
    at d (http://localhost:3000/static/js/bundle.js:1816:7)
    at BalCard
    at main
    at bal-app
    at d (http://localhost:3000/static/js/bundle.js:1816:7)
    at BalApp
    at App (http://localhost:3000/static/js/bundle.js:874:76)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

```

## Conclusion
We have still React DOM Exceptions all over the framework. Workaround not always possible.

**Comment by chester23491** [comment]
Issue also exists when removing `bal-button` inside`bal-button-group`.

Can you please give us any estimates when this bug is solved?

**Comment by hirsch88** [comment]
Hi @chester23491, radio and checkbox have now a option prop to avoid this error. Select is in progress.
To fix this bug in general we need to introduce Shadow DOM and this is very expensive, therefore we will maybe start with it in q4 2023
